source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FDTake_Example', :exclusive => true do
  pod "FDTake", :path => "../" 
  pod "CTAssetsPickerController", "~> 3.3.2-alpha"
end

target 'FDTake_Tests', :exclusive => true do
  pod "FDTake", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
